cdsp/config/routes.rb
Cdsp::Application.routes.draw do
  resources :cdspps

end

cdsp/app/models/cdspp.rb
class Cdspp < ActiveRecord::Base
end

cdsp/app/controllers/cdspps_controller.rb
class CdsppsController < ApplicationController
  # GET /cdspps
  # GET /cdspps.xml
  def index
    @cdspps = Cdspp.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @cdspps }
    end
  end

  # GET /cdspps/1
  # GET /cdspps/1.xml
  def show
    @cdspp = Cdspp.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @cdspp }
    end
  end

  # GET /cdspps/new
  # GET /cdspps/new.xml
  def new
    @cdspp = Cdspp.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @cdspp }
    end
  end

  # GET /cdspps/1/edit
  def edit
    @cdspp = Cdspp.find(params[:id])
  end

  # POST /cdspps
  # POST /cdspps.xml
  def create
    @cdspp = Cdspp.new(params[:cdspp])

    respond_to do |format|
      if @cdspp.save
        format.html { redirect_to(@cdspp, :notice => 'Cdspp was successfully created.') }
        format.xml  { render :xml => @cdspp, :status => :created, :location => @cdspp }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @cdspp.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /cdspps/1
  # PUT /cdspps/1.xml
  def update
    @cdspp = Cdspp.find(params[:id])

    respond_to do |format|
      if @cdspp.update_attributes(params[:cdspp])
        format.html { redirect_to(@cdspp, :notice => 'Cdspp was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @cdspp.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /cdspps/1
  # DELETE /cdspps/1.xml
  def destroy
    @cdspp = Cdspp.find(params[:id])
    @cdspp.destroy

    respond_to do |format|
      format.html { redirect_to(cdspps_url) }
      format.xml  { head :ok }
    end
  end
end

cdsp/app/helpers/cdspps_helper.rb
module CdsppsHelper
end

cdsp/app/views/cdspps/_form.html.erb
<%= form_for(@cdspp) do |f| %>
  <% if @cdspp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cdspp.errors.count, "error") %> prohibited this cdspp from being saved:</h2>

      <ul>
      <% @cdspp.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br />
    <%= f.calendar_date_select :date, :time => true, :popup => true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

cdsp/app/views/cdspps/edit.html.erb
<h1>Editing cdspp</h1>

<%= render 'form' %>

<%= link_to 'Show', @cdspp %> |
<%= link_to 'Back', cdspps_path %>

cdsp/app/views/cdspps/index.html.erb
<h1>Listing cdspps</h1>

<table>
  <tr>
    <th>Date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cdspps.each do |cdspp| %>
  <tr>
    <td><%= cdspp.date %></td>
    <td><%= link_to 'Show', cdspp %></td>
    <td><%= link_to 'Edit', edit_cdspp_path(cdspp) %></td>
    <td><%= link_to 'Destroy', cdspp, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cdspp', new_cdspp_path %>

cdsp/app/views/cdspps/new.html.erb
<h1>New cdspp</h1>

<%= render 'form' %>

<%= link_to 'Back', cdspps_path %>

cdsp/app/views/cdspps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Date:</b>
  <%= @cdspp.date %>
</p>


<%= link_to 'Edit', edit_cdspp_path(@cdspp) %> |
<%= link_to 'Back', cdspps_path %>